### ISSUE TITLE
Functions contained in subroutine exposed to Python

### ISSUE THREAD

**Issue by reuterbal** [jameskermode/f90wrap#101]
Hi,

thanks for this really useful project!

I noticed a problem with a situation like the following:
```fortran
subroutine routine_member_procedures(in1, in2, out1, out2)
  ! Test member subroutine and function
  implicit none
  integer, intent(in) :: in1, in2
  integer, intent(out) :: out1, out2
  integer :: localvar 
  
  localvar = in2
  call member_procedure(in1, out1)
  out2 = member_function(out1)
contains
  subroutine member_procedure(in1, out1)
    ! This member procedure shadows some variables and uses
    ! a variable from the parent scope
    implicit none
    integer, intent(in) :: in1
    integer, intent(out) :: out1
    
    out1 = 5 * in1 + localvar
  end subroutine member_procedure
  function member_function(a) result(b)
    implicit none
    integer, intent(in) :: a
    integer :: b
    
    b = 3 * a + 2
  end function member_function
end subroutine routine_member_procedures
```

In this case I would expect f90wrap to expose only `routine_member_procedures` in the Python module, not any of the contained routines. However, while the contained subroutine `member_procedure` is omitted, the contained function `member_function` is included in the generated interface, causing import errors.

I generated the Python module as follows:
```
~> gfortran -c -fpic test.f90
~> f90wrap -m test test.f90 
~> f2py-f90wrap -c -m _test test.o f90wrap_*.f90                                                                                                                                                           
```

However, when trying to import this produces an error due to the missing symbol:
```
~> python3
Python 3.7.1 (default, Nov 21 2018, 09:56:53) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../test.py", line 2, in <module>
    import _test
ImportError: .../_test.cpython-37m-x86_64-linux-gnu.so: undefined symbol: member_function_
```

The produced `test.py` looks as follows:
```python
from __future__ import print_function, absolute_import, division
import _test
import f90wrap.runtime
import logging

def routine_member_procedures(in1, in2):
    """
    out1, out2 = routine_member_procedures(in1, in2)
    
    
    Defined at test.f90 lines 1-19
    
    Parameters
    ----------
    in1 : int
    in2 : int
    
    Returns
    -------
    out1 : int
    out2 : int
    
    """
    out1, out2 = _test.f90wrap_routine_member_procedures(in1=in1, in2=in2)
    return out1, out2

def member_function(a):
    """
    b = member_function(a)
    
    
    Defined at test.f90 lines 21-26
    
    Parameters
    ----------
    a : int
    
    Returns
    -------
    b : int
    
    """
    b = _test.f90wrap_member_function(a=a)
    return b

```

**Comment by jameskermode** [comment]
Thanks for reporting. This is due to a limitation of my parser, which doesn’t know about inner functions. As a work around you could try to use the `--skip` command line option to remove them.

**Comment by reuterbal** [comment]
Thanks for the quick reply! I will keep the `--skip` option in mind to mitigate such situations.

**Comment by jameskermode** [comment]
Alternatively, a pull request to fix the parser would be very welcome :-)

**Comment by reuterbal** [comment]
Any hints on where to look? Since the inner subroutine is treated correctly, it might be possible to do something similar for the function. But I haven't found the reason for that different behaviour in `parser.py`.
No promises, though ;-)

**Comment by jameskermode** [comment]
One possibility would be to modify around here to skip over the inner subroutines, if we are currently inside one already:

https://github.com/jameskermode/f90wrap/blob/master/f90wrap/parser.py#L602

Or we could add some special attribute to flag them as inner functions which could later be removed using something similar to

https://github.com/jameskermode/f90wrap/blob/master/f90wrap/transform.py#L188

**Comment by reuterbal** [comment]
OK, I'll have a look in a quiet minute. Many thanks.
