### ISSUE TITLE
shared flag in .so compilation

### ISSUE THREAD

**Issue by pogam** [jameskermode/f90wrap#111]
I am not sure why, but I need to add '-shared' flag in the last command of the .so compilation to make it run. 

For example the array-fixed example failed at 
 ```
/usr/bin/gfortran -Wall -g -Wl,-rpath,/lib -L/lib ./src.linux-x86_64-2.7/_ExampleArraymodule.o ./src.linux-x86_64-2.7/src.linux-x86_64-2.7/fortranobject.o ./f90wrap_library.o -L. -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/home/paugam/anaconda2/envs/gui/lib -lsrc -lpython2.7 -lgfortran -o ./_ExampleArray.so
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
I need to add `-shared` for the command to make it pass.

I am using f90wrap v0.1.0

Thanks for help.

**Comment by jameskermode** [comment]
What platform are you on? Could you try updating to latest f90wrap as well?

**Comment by pogam** [comment]
ubuntu18.04 with anaconda running a python 2.7 environement
I managed to update f90wrap in my env to f90wrap v0.1.4 
and the compilation is now working.
Thanks

**Comment by jameskermode** [comment]
OK great. I'll close this issue now then.
