### ISSUE TITLE
f90wrap produces type mismatch for character dummy argument

### ISSUE THREAD

**Issue by jmpetit** [jameskermode/f90wrap#113]
Hello,

first let me thank you for this very nice piece of code. I think it can save my day for using F95 code with derived types, if I can figure out how to handle character dummy arguments.

I have a simple code with a single function with a character dummy argument.
[ioutils.txt](https://github.com/jameskermode/f90wrap/files/4487954/ioutils.txt)

f90wrap produces a wrapper that wants to send a real(4) to the routine instead of character:
[f90wrap_ioutils.txt](https://github.com/jameskermode/f90wrap/files/4487961/f90wrap_ioutils.txt)

So f2py-f90wrap exit with an error when trying to compile the wrapper with gfortran:
[error.txt](https://github.com/jameskermode/f90wrap/files/4487976/error.txt)

I've tried with fixed character length (character*100) or assumed length (character*(*)) to no avail. I've even added some extra conversion in kind.cmap, not working either:
[f2py_f2cmap.txt](https://github.com/jameskermode/f90wrap/files/4488000/f2py_f2cmap.txt)

What should I do to allow character arguments to routines ?

Thanking you in advance for your support,

best, Jean-Marc Petit

**Comment by jmpetit** [comment]
Hello again,

I had a closer look at the string example and found the solution to my problem above. instead of the old declaration:
`    character*(*) :: base_name
`
I must use the new syntax:
`    character(*) :: base_name
`
Notice the dropping of the first `*` character.
I then found a limitation to the wrapper. The character string should contain only ASCII literal, or at least characters that fit insinde a single byte:
`In [6]: text = 'abc'                                                            

In [7]: n = len(text)                                                           

In [8]: lib.trim_f95(n, text)                                                   
           3           3 abc
`
If now one put, say, accentuated french characters, then there is an error:
`In [9]: text = 'àçé'                                                            

In [10]: n = len(text)                                                          

In [11]: lib.trim_f95(n, text)                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-5710cca7a4e4> in <module>
----> 1 lib.trim_f95(n, text)

~/Research/Simulator/SurveySimOSSOS/GIT/testF90WRAP/TestF90WRAP.py in trim_f95(n, base_name)
     26 
     27         """
---> 28         _TestF90WRAP.f90wrap_trim_f95(n=n, base_name=base_name)
     29 
     30     _dt_array_initialisers = []

TypeError: function takes exactly 5 arguments (1 given)
`
Best, Jean-Marc

**Comment by jameskermode** [comment]
Thanks for the update. If the `character*(*)` syntax is valid Fortran then I'd be happy to receive a pull request that fixes the parser to work with this syntax as well.

I'm not up to date on Fortran support for unicode strings, and I'm not surprised that this causes difficulties. Will this be a critical limitation for you in practice?

**Comment by jmpetit** [comment]
Hi again,
in my previous comment, I forgot the most important part to fix the problem. I needed also to drop the part on `character` in the `kind_map` file. That made the trick, together with dropping the `*` character in the declaration.

Best, Jean-Marc

**Comment by jameskermode** [comment]
OK - for character strings, the lengths should be set in with the `--string-lengths` argument, rather than with the kind map. There is also a `--default-string-length` argument to set the default. See `f90wrap -h` for a bit more detail.

**Comment by jmpetit** [comment]
Thanks for your answer, James.

The unicode limitation is not a problem for me, as long as I remember not to use them in file names. Normally, I tend to restrict myself to ASCII characters.

Looking at Fortran 2003 specification (and I guess this is also valid for Fortran 95 or 90), the normal character declaration is
`character (*)
`
but at least gfortran still accepts the old Fortran 77 style
`character*(*)
`
So I don't think this requires a fix of the parser, but rather just a comment in the README file or somewhere.

Thanks for the hard work, best, Jean-Marc

**Comment by jameskermode** [comment]
OK, thanks, in that case I'll close this issue - please open a new one if something else comes up.
