### ISSUE TITLE
Error while installing via pip

### ISSUE THREAD

**Issue by EverLookNeverSee** [jameskermode/f90wrap#118]
Hi there
I got this error:
![f90wrap](https://user-images.githubusercontent.com/57490926/85390827-9d5ea400-b55e-11ea-9c62-6160ddf2dc15.png)

**Comment by jameskermode** [comment]
I don't see an error in that screenshot. Can you send the complete log? You may find it easier to clone the repository and run `python setup.py install` manually.

**Comment by EverLookNeverSee** [comment]
![Screenshot_20200623_194932](https://user-images.githubusercontent.com/57490926/85422356-c301a280-b58a-11ea-8f36-85d050d13aec.png)

I tried to install manually, but i got same error message.
