### ISSUE TITLE
ifdef fortran MACROS

### ISSUE THREAD

**Issue by landsito** [jameskermode/f90wrap#141]
Hi!

Noticed that when having:

```
#ifdef DBLE
integer, parameter         :: rp = 8
#else
integer, parameter         :: rp = 4
#endif

```
the following interface is generated by f90wrap:
```
! Module function defined in file function.F90

 subroutine f90wrap_function__get__rp(f90wrap_rp)
     use function, only: function_rp => rp
     implicit none
     integer, intent(out) :: f90wrap_rp

     f90wrap_rp = function_rp
 end subroutine f90wrap_function__get__rp
 
 subroutine f90wrap_function__get__rp(f90wrap_rp)
     use function, only: function_rp => rp
     implicit none
     integer, intent(out) :: f90wrap_rp

     f90wrap_rp = function_rp
 end subroutine f90wrap_function__get__rp
 
```
It looks like f90wrap is overlooking the fortran compiling MACROS. Is there a way to overcome this? or does f90wrap require an update?

Thanks

**Comment by jameskermode** [comment]
This is not a bug per se, but in any case thanks for the reminder. I will make a new release to PyPI once a couple of the currently outstanding issues have bene resolved.

**Comment by jameskermode** [comment]
Apologies, I respond to the wrong issue. Reopening

**Comment by jameskermode** [comment]
The way to deal with this is to pre-process your Fortran source before passing it to `f90wrap`. Here is an example Makefile showing how this can be done

https://github.com/libAtoms/QUIP/blob/public/quippy/Makefile

**Comment by jameskermode** [comment]
(and regarding your earlier comment about the pip version, I'll make a new release once a couple of the currently outstanding issues have been addressed).

**Comment by jameskermode** [comment]
OK to close this issue?

**Comment by landsito** [comment]
Yes, thanks
