### ISSUE TITLE
use of undeclared identifier 'setjmpvalue'

### ISSUE THREAD

**Issue by uturuncoglu** [jameskermode/f90wrap#144]
I am getting following error when I try to wrap very simple application under Mac OS Catalina.

```
/var/folders/kw/drgwhfr55bjdpq233crlywfhbjq1zk/T/tmpi_s7bxbd/src.macosx-10.15-x86_64-3.9/_wrappermodule.c:232:1: error: use of undeclared identifier 'setjmpvalue'
setjmpvalue = setjmp(environment_buffer);
^
/var/folders/kw/drgwhfr55bjdpq233crlywfhbjq1zk/T/tmpi_s7bxbd/src.macosx-10.15-x86_64-3.9/_wrappermodule.c:233:5: error: use of undeclared identifier 'setjmpvalue'
if (setjmpvalue != 0) {
    ^
```

I was thinking that this issue is resolved recently https://github.com/jameskermode/f90wrap/issues/135 and PR https://github.com/jameskermode/f90wrap/pull/139 but it still does not allow me to compile using following commands. 

```
f90wrap -m wrapper wrapper.f90
f2py-f90wrap -c -m _wrapper f90wrap*.f90 -L. -lwrapper
```

I also tried to install recent version of the **f90wrap** but still same,

```
wget https://github.com/jameskermode/f90wrap/archive/v0.2.3.tar.gz
python3 -m pip install v0.2.3.tar.gz
```

Here is the detail of the environment, 

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/10.2.0_4/libexec/gcc/x86_64-apple-darwin19/10.2.0/lto-wrapper
Target: x86_64-apple-darwin19
Configured with: ../configure --build=x86_64-apple-darwin19 --prefix=/usr/local/Cellar/gcc/10.2.0_4 --libdir=/usr/local/Cellar/gcc/10.2.0_4/lib/gcc/10 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-10 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 10.2.0_4' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk SED=/usr/bin/sed
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (Homebrew GCC 10.2.0_4) 
```

**Comment by uturuncoglu** [comment]
Just to update, I fixed by applying same patch that is explained in the PR. I think that latest release does not include the patch.

**Comment by jameskermode** [comment]
Yes, that is correct. New release planned soon, once a couple of the more urgent outstanding issues have been resolved. I'll close this one now, though, if that's OK?

**Comment by uturuncoglu** [comment]
@jameskermode yes, you could close it. BTW, thanks for very nice tool. I need to use Fortran derived data support for my project to create connection with Python. I just wonder that do you have any document etc. for very toy application that demonstrates the implementation and usage. I am currently referencing example directory for it but it has lots of staff. Anyway, that's for your kindly interest.

**Comment by jameskermode** [comment]
You're welcome, thanks! Have a look at the [f90wrap paper](https://iopscience.iop.org/article/10.1088/1361-648X/ab82d2) and this [tutorial notebook](https://github.com/jameskermode/f90wrap/blob/master/docs/tutorials/f90wrap-demo-feb-2020.ipynb)
