### ISSUE TITLE
setjmpvalue undeclared error on Ubuntu

### ISSUE THREAD

**Issue by sbland** [jameskermode/f90wrap#148]
As @bernardopacini below I get the `setjmpvalue undeclared` error on Ubuntu 20.04 using Numpy  1.20.0 and gfortran 9.3. Reproducable by calling `make` from examples/derivedtypes.

_I want to add that I now run into this issue on a fresh installation of Ubuntu 20.04 with GCC9.3 and Numpy 1.20.0. I imagine something changed with the newer Numpy version causing this "replace" line to fail._

_Originally posted by @bernardopacini in https://github.com/jameskermode/f90wrap/issues/139#issuecomment-771423115_

**Comment by jameskermode** [comment]
This was addressed in the PR you link to, so should already be fixed in the development version of `f90wrap`. Can you try to clone the repo and install from there? 

```
git clone https://github.com/jameskermode/f90wrap
pip install ./f90wrap
```

**Comment by sbland** [comment]
Ah great thanks. I had the repo but had installed via `pip install f90wrap`. Installing directly works!

**Comment by jameskermode** [comment]
Thanks for confirming. I’ll close this now, and will try to make a new release soon so that pip install also works.
