### ISSUE TITLE
IndentationError with python 3.9

### ISSUE THREAD

**Issue by tilmantroester** [jameskermode/f90wrap#153]
Some of the generated python wrapper code causes `IndentationError` with python 3.9. The same code works on 3.8.

```
_pyhmcode.f90wrap_halomod__set__dmonly_neutrino_halo_mass_correction(self._handle, \
    ^
IndentationError: expected an indented block
```
The offending block is
```python
@dmonly_neutrino_halo_mass_correction.setter
    def dmonly_neutrino_halo_mass_correction(self, \
        dmonly_neutrino_halo_mass_correction):
        \
            _pyhmcode.f90wrap_halomod__set__dmonly_neutrino_halo_mass_correction(self._handle, \
            dmonly_neutrino_halo_mass_correction)
```

Python 3.9 doesn't seem to like the empty line continuation. The following works on 3.8 but fails on 3.9:
```python
def f():
    \
    pass
```
I can't see anything in the 3.9 change log that mentions this though.

**Comment by jameskermode** [comment]
Thanks for reporting. I guess we don't need the '\' here in any case since the continuation is not needed within parenthesis. A PR to improve the logic would be most welcome, or I will probably get to it eventually.

**Comment by tilmantroester** [comment]
Thanks for the quick reply. Where would I have to look to fix this?

**Comment by jameskermode** [comment]
https://github.com/jameskermode/f90wrap/blob/master/f90wrap/codegen.py#L111

could also just allow a larger `max_length` to be passed in from the command line.

**Comment by jameskermode** [comment]
Ha. In fact the latter idea is already possible with `--py-max-line-length` command line option to `f90wrap`, which might solve your problem?

https://github.com/jameskermode/f90wrap/blob/master/scripts/f90wrap#L157

**Comment by tilmantroester** [comment]
Setting `--py-max-line-length=200` indeed solves this, thanks! I think I also fixed offending part of the line-splitting code (see #154).
