### ISSUE TITLE
more explanations on the provided examples

### ISSUE THREAD

**Issue by habtie-phys** [jameskermode/f90wrap#156]
Two steps are given to wrap a Fortran source code to python.  the steps are given below. 
                                             
                                         f90wrap -m MODULE F90_FILES
                                        f2py -c -m _MODULE OBJ_FILES f90wrap_*.f90 *.o

 Each term in the lines above is explained except the '' OBJ_FILES'' in the second line of the steps.  Could you add an explanation to this one? Thanks!

**Comment by jameskermode** [comment]
This just means the object files (plus possibly libraries as well) that contain your compiled code. It’s redundant with the `*.o` at the end, so I’ll clean this up and improve the explanation.
