### ISSUE TITLE
Help wrapping a project

### ISSUE THREAD

**Issue by Mobbybobby** [jameskermode/f90wrap#159]
Hi,

I'm trying to wrap this project: https://github.com/lanl/clog. What I need is the dedx_bps routine in the dedx.f90 file.
Optimally I would like to have in on windows but since f90wrap on windows didn't install I tried Linux. 

I wrapped it with the commands: 

` f90wrap -m BPS dedx.f90`

and

`f2py-f90wrap -c -m _BPS f90wrap_toplevel.f90`.

When I tried to import the module in a test it gave me the error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import BPS
  File "....../BPS/BPS.py", line 2, in <module>
    import _BPS
ImportError: ....../BPS/_BPS.cpython-36m-x86_64-linux-gnu.so: undefined symbol: kqm1_
```

This is my test since I know what the result should be:
```
import numpy as np
import scipy.constants as constants
import BPS
ne = np.array([10 ** 20, 0.1667E20], dtype='float', order='F')
Te = np.array([1 / 0.2, 1 / 0.2], dtype='float', order='F')
E = 8000
Z = 6
scale = 1.e-7
mp = 12 * constants.u * constants.c ** 2 / constants.eV
zb = np.array([-1, 6], dtype='float', order='F')
mb = np.array([510.998902, 0.1126E08], dtype='float', order='F')
result = BPS.dedx_bps(scale=scale, ep=float(E), zp=float(Z), mp=mp, betab=Te, zb=zb, mb=mb, nb=ne, nni=int(1))
print(result)
```

I would love to wrap this project to be useable on windows sometime in the meantime i want it working on linux atleast.

I hope someone can help me wrapping.

**Comment by jameskermode** [comment]
You need to link the wrapper to your compiled code, i.e. change the `f2py-f90wrap` line to include your object files or static libraries. For example, if you've compiled it into a `libBPS.a` static library in the current directory you could do

```bash
f2py-f90wrap -c -m _BPS f90wrap_toplevel.f90 -lBPS
```

There's no deep reason why f90wrap shouldn't work on Windows, just that I haven't tried to do it since I don't have access to a Windows machine.

**Comment by Mobbybobby** [comment]
I can't call f90wrap in cmd on windows. Even though it's on PATH...

Back to Linux:

When creating the wrapper do I have to include all files the function needs or is the one it is in suffice?
So do I have to do:

`f90wrap -m BPS dedx.f90`

or

`f90wrap -m BPS dedx.f90 common.f90 ferf.f vars.f90 mathvars.f90 physvars.f90`.

same question when wrapping. Which files need to be included? (I created .o files for each file)

**Comment by jameskermode** [comment]
The wrapper only needs to wrap the functions you want to call from Python, but it needs to be linked against all object files which those routines depend on, or you’ll get undefined symbol errors like you reported above.

**Comment by Mobbybobby** [comment]
Thanks. It works now. But the test doesn't give the right result. I executed the function in python and in fortran with the same inputs but they yield different results...

**Comment by Mobbybobby** [comment]
Do have to pay attention to how I call the function in python? Am I doing it wrong or did the wrapping not work properly? do I have to change the Fortran code in anyway prior to wrapping?

This is the header of the function:
```
      SUBROUTINE dedx_bps(nni, scale, ep, zp, mp, betab, zb, mb, nb,  &
            dedx_tot, dedx_i, dedx_e, dedxc_tot, dedxc_i, dedxc_e, & 
            dedxq_tot, dedxq_i, dedxq_e)
      USE physvars
      USE mathvars      
        IMPLICIT NONE                                      ! Plasma:
        INTEGER,                     INTENT(IN)  :: nni    !  number of ions
        REAL,    DIMENSION(1:nni+1), INTENT(IN)  :: betab  !  temp array [1/keV]
        REAL,    DIMENSION(1:nni+1), INTENT(IN)  :: mb     !  mass array [keV]
        REAL,    DIMENSION(1:nni+1), INTENT(IN)  :: nb     !  density [1/cc]
        REAL,    DIMENSION(1:nni+1), INTENT(IN)  :: zb     !  charge array
                                                           !
                                                           ! Projectile  
        REAL,                        INTENT(IN)  :: ep     !  projectile energy [keV]
        REAL,                        INTENT(IN)  :: mp     !  projectile mass   [keV]
        REAL,                        INTENT(IN)  :: zp     !  projectile charge

                                                              ! dE/dx [MeV/micron]
        REAL,                        INTENT(IN)  :: scale     !  1.e-7 converts KeV/cm to MeV/mu-m
        REAL,                        INTENT(OUT) :: dedx_tot  !  electron + ion
        REAL,                        INTENT(OUT) :: dedx_i    !  ion contribution
        REAL,                        INTENT(OUT) :: dedx_e    !  electron contribution
        REAL,                        INTENT(OUT) :: dedxc_tot !  classical
        REAL,                        INTENT(OUT) :: dedxc_i   !  classical
        REAL,                        INTENT(OUT) :: dedxc_e   !  classical
        REAL,                        INTENT(OUT) :: dedxq_tot !  quantum
        REAL,                        INTENT(OUT) :: dedxq_i   !  quantum
        REAL,                        INTENT(OUT) :: dedxq_e   !  quantum

        REAL,    DIMENSION(1:nni+1)  :: kkb2, aab, ab2, c1b, c2b, c3b,c4b, eetb
        REAL,    DIMENSION(1:nni+1)  :: mpb, mbpb, mtotb, mtotpb, mratpb, bpb, cpb
        REAL     :: vp, vp2, zp2, kk, k2, kd, kd2, c1, c2, c3, c4, eta, a, b, c, a2
        REAL     :: dedxc_s, dedxc_r, dedxc_r1, dedxc_r2, dedxq, mt, mr, xx
        REAL     :: dedxc_s_e, dedxc_r_e, dedxc_s_i,dedxc_r_i
!       REAL     :: ln_dedx_bps
        INTEGER  :: ib, NNB
```
The test I wrote in python is in the first post.

**Comment by Mobbybobby** [comment]
The result should be :   
`0.5936609902872E-03   0.4888359574407E-06   0.5931721543298E-03   0.6004169917162E-03   0.4888964401557E-06   0.5999280952761E-03  -0.6756001429026E-05  -0.6048271503922E-10  -0.6755940946311E-05`

but is :
`-0.032989419996738434, 0.00014330580597743392, -0.03313272446393967, -0.03298914059996605, 0.00014330586418509483, -0.03313244506716728, -2.79809455605573e-07, -6.002685848383038e-11, -2.79749428955256e-07`

**Comment by jameskermode** [comment]
This is beyond the scope of an issue with f90wrap: correct usage of this Fortran library is not something I can help you with. If you can produce a minimal working example (i.e. a single subroutine, independent of any external packages) that shows an error in how f90wrap is calling the code then please open a new issue. You might find the comprehensive set of examples in `f90wrap/examples` helpful.
