### ISSUE TITLE
multidimensional arrays in derived types broken if compiled with long integers as default

### ISSUE THREAD

**Issue by Haettig** [jameskermode/f90wrap#164]
@jameskermode 
While trying to use f90wrap to develop interfaces for the TURBOMOLE program package, I faced a problem with multidimensional arrays in user-defined types, like:
```
type(my_own_type)
    real(8), allocatable :: xyz(:,:)
end type
```
since the package used by default long integers, i.e. with gfortran the flag -fdefault-integer-8, I use this also to compile the Fortran routines that I want to wrap. 
What happens then is when this variables are printed with the print function in Python that only 1D arrays appear correctly, while for all multidimensional arrays only the first dimension is non-zero and all other dimensions are set to 0, so that the arrays are not accessible in Python.

The reason for this is that the f90wrap*.f90 routines that are generated by f90wrap use Fortran default integers for the declaration of output variables like nd, dtype, and dshape (in particular, the latter is the problem) of functions that are called from C, instead of using integer(c_int) with the c_int from the iso_c_binding module.

Can we get this fixed?

**Comment by jameskermode** [comment]
Thanks for reporting. A pull request to change to `integer(c_int)` would be welcome, but I won't have time to write and test this myself in the near future.
