### ISSUE TITLE
Python 3.11 support 

### ISSUE THREAD

**Issue by jan-janssen** [jameskermode/f90wrap#168]
Hi @jameskermode , 

As conda-forge is moving forward in adding support for Python 3.11 we noticed that `f90wrap` is not yet compatible. If you have a moment it would be great to add Python 3.11 support. 
https://github.com/conda-forge/f90wrap-feedstock/pull/32

Best, 

Jan

**Comment by jameskermode** [comment]
Thanks for reporting. Yes, I'd noticed Python 3.11 failures in f90wrap's wheel-building CI so this is on my radar. I'll take a look ASAP and report back here and to [https://github.com/conda-forge/f90wrap-feedstock/pull/32](https://github.com/conda-forge/f90wrap-feedstock/pull/32)

**Comment by jan-janssen** [comment]
Hi @jameskermode I just wanted to check back on this issue, did you have time to take a look at it? My issue is that the `lammps` package depends on `quippy` and `quippy` itself depends on `f90wrap`, which currently prevents me from updating the `lammps` package to python 3.11. The alternative option is to remove `quippy` support from the `lammps` conda forge package so that we can continue with the migration, but before I do so, I wanted to cycle back with you.

**Comment by jameskermode** [comment]
Nope, I've not had time to look at this at all. I might managed next week but can't make any promises. If you would be able to dig into it and report errors here I'll be very willing to try to help resolve it.

**Comment by jan-janssen** [comment]
It seems to be this part:
```
 f90wrap/arraydatamodule.c: In function 'PyInit_arraydata':
  f90wrap/arraydatamodule.c:171:28: error: lvalue required as left operand of assignment
    171 |   Py_TYPE(&PyFortran_Type) = &PyType_Type;
        |                            ^
```

**Comment by jameskermode** [comment]
Think I've figured this out. Once the PR passes for both pre- and post- Py 3.11 I'll do a new release you can use for conda-forge.

**Comment by jan-janssen** [comment]
That would be great - I look forward to it.

**Comment by jameskermode** [comment]
Seems to work. v0.2.11 is being built and released now, should be on PyPI in 30 mins or so.

This still leaves #169, Windows support.

**Comment by jan-janssen** [comment]
Thanks a lot - this solved the issue https://github.com/conda-forge/f90wrap-feedstock/pull/36
