### ISSUE TITLE
arguments when calling routine with output variables intent(out)

### ISSUE THREAD

**Issue by davidovitch** [jameskermode/f90wrap#18]
I am trying to get going with ```f90wrap```. On my system (Arch Linux 64 bit) the example ```mockderivetype``` does not pass all its tests. I am running in a pip updated virtualenv (python 2.7). For reference, the traceback I get is:
```python
File "f90wrap/examples/mockderivetype/test.py", line 30, in <module>
    result = use_a_type.do_stuff(8)

TypeError: do_stuff() takes exactly 2 arguments (1 given)
```

As far as I understand the error, the arguments list in the Fortran sources contains both input and output variables, where ```intent(in/out)``` specifies the nature of the specific arguments. For the case above see [f90wrap/examples/mockderivetype/fwrap.f90 line 19](https://github.com/jameskermode/f90wrap/blob/master/examples/mockderivetype/fwrap.f90#L19). But the Python call also requires to pass on the output variable. From the generated ```mockdt.py``` I get:
```python

@staticmethod
def do_stuff(factor, out):
    """
    do_stuff(factor, out)
    
    
    Defined at fwrap.fpp lines 23-64
    
    Parameters
    ----------
    factor : float
    out : float
    
    This is the module which defines the type 'atype'
    Here's a routine that does something
    """
    _mockdt.f90wrap_do_stuff(factor=factor, out=out)

```
Is that the intended behaviour, or maybe I am missing something obvious here (I have experience with Python, but only some basic Fortran)?

**Comment by jameskermode** [comment]
I can confirm this test is currently broken. I will fix it ASAP, and set up automated unit testing to prevent these kinds of regressions occurring in future.

**Comment by davidovitch** [comment]
There is one more thing I am not sure about: are wrapped subroutines with variables as ```intent(out)``` supposed to return those values when calling them in Python? I can do this with a wrapped function:
```fortran
function return_value_func(val_in) result(val_out)
    integer(4) val_in, val_out
    val_out = val_in + 10
end function return_value_func
```
will be wrapped such that when calling ```return_value_func()``` in Python returns the expected value, for example:
```python
from somemodule import library as lib
val_in = 1
val_out = lib.return_value_func(val_in)
val_out
>>> 11
```
However, a similar example with a ```subroutine``` does not return the output variables.
```fortran
subroutine return_value_sub(val_in, val_out)
    integer(4), INTENT(in) :: val_in
    integer(4), INTENT(out) :: val_out
    val_out = val_in + 10
end subroutine return_value_sub
```
Further, both input and output variables are required when calling the subroutine from Python:
```python
from somemodule import library as lib
val_in = 1
val_out = 0
val_out2 = lib.return_value_sub(val_in=val_in, val_out=val_out)
val_out
>>> 0
val_out2
>>> None
```

**Comment by jameskermode** [comment]
This is a bug in f90wrap. Fortran `intent(out)` arguments should become return values in Python. This is a regression in the current code which I need to look into.

**Comment by davidovitch** [comment]
Thanks for clarifying. Since I have little Fortran experience, I was not sure if this was me or f90wrap.

**Comment by jameskermode** [comment]
This bug should be fixed in commit c1a43b5 - let me know if this works for you and I will close this issue. Sorry for the delay in finding time to fix this.

**Comment by davidovitch** [comment]
Sorry for the late response. This issue is indeed fixed now, thanks!!

I was also trying this with an array as output, for example:

```fortran
SUBROUTINE create_array(array)
    REAL(idp), DIMENSION(:), ALLOCATABLE, INTENT(out) :: array
    INTEGER :: i
    
    if (ALLOCATED(array))   DEALLOCATE(array)
    ALLOCATE(array(10))
    
    DO i=1,10
        array(i) = i*10.0_idp
    ENDDO
END SUBROUTINE create_array
```

but then I realized this actually doesn't work with a pointer/allocable as a subroutine argument based on the output:

```
DEBUG:root:removing routine create_array due to allocatable/pointer arguments
```
I guess this means that in general the allocation of arrays can only take place in Python?

**Comment by jameskermode** [comment]
This is correct - allocatable subroutine arguments are not currently supported. However, allocatable arrays can be used inside derived types, so you can allocate/deallocate from Fortran as well as Python. 

Here's a common pattern I use with constructor and destructor routines (code not tested...)

~~~fortran

module derivedtype_module

type example
  real(dp), allocatable :: x(:)
end type

interface initialise
  module procedure example_initialise
end interface

interface finalise
   module procedure example_finalise
end interface

contains

subroutine example_initialise(this, size)
    type(example), intent(inout) :: this
    integer, intent(in) :: size

    call finalise(this)
    allocate(this%x(size))
end subroutine

subroutine example_finalise(this)
    type(example), intent(inout) :: this
    if (allocated(this%x)) deallocate(this%x)
end subroutine

end module
~~~

**Comment by davidovitch** [comment]
Thanks! That is a quite nice example of how to deal with the allocation/deallocation from either Python or Fortran side.

**Comment by jameskermode** [comment]
Marking as closed now.
