### ISSUE TITLE
Binary Wheels for Mac

### ISSUE THREAD

**Issue by robertschweizer** [jameskermode/f90wrap#203]
Thanks a lot for your work on this project!

I'm currently trying to install the QGIS plugin https://github.com/UMEP-dev/UMEP-processing on an M1 Mac. 

I noticed that binary wheels of f90wrap are only available for Mac for older versions (0.2.12 for x86_64, 0.2.11 for arm64). Passing `--prefer-binary` makes pip use them (I hope I won't see issues at runtime).

It looks like work on automatically building them started in https://github.com/jameskermode/f90wrap/pull/185, but is not complete yet.

It would be really great to get Mac binaries of the latest version on PyPI as well.

**Comment by jameskermode** [comment]
Should be ressolved with release v0.2.14 on PyPI. Please re-open if there's stilla problem!
