### ISSUE TITLE
elemental function problem

### ISSUE THREAD

**Issue by piotradam** [jameskermode/f90wrap#25]
Hi,
First of all: what a great idea! I have a collaborator who can only work with Fortran, and we have been re-inventing the proverbial wheel for all the simple (in Python) things that are tedious in Fortran.

I was trying f90wrap and noticed that a simple elemental function poses a problem.
Example:

module elemental_module
  implicit none 
contains
  elemental real(kind=8) function sinc(x)
    real(kind=8), intent(in) :: x
    if(abs(x).gt.1d-5) then
       sinc = sin(x)/x
    else
       sinc = 1.0d0
    endif
    return
  end function sinc
end module elemental_module

I have used the following commands to build it
 f90wrap -m elmod elemental_module.f90 -k kind_map -v
 f2py-f90wrap --fcompiler=gfortran -I. --build-dir . -c -m _elmod elemental_module.f90 f90wrap*.f90

The problem is, I believe in f90wrap_elemental_module.f90 as it uses elemental as a type for ret_sinc

Cheers

Piotr

**Comment by jameskermode** [comment]
Hi Piotr, thanks for reporting and sorry to be slow getting back to you- I've reproduced your problem and hope to be able to look into finding a fix tomorrow.

**Comment by jameskermode** [comment]
This is a parsing issue. As a workaround, if you switch the order of `elemental` attribute and the return type `real(kind=8)` then it works correctly:

```fortrtan
module elemental_module
implicit none
contains
real(kind=8) elemental function sinc(x)
real(kind=8), intent(in) :: x
if(abs(x).gt.1d-5) then
sinc = sin(x)/x
else
sinc = 1.0d0
endif
return
end function sinc
end module elemental_module
```

**Comment by jameskermode** [comment]
Parser is now fixed so this work with either ordering of ``elemental`` and the return type.

**Comment by piotradam** [comment]
Thanks. I will give it a shot
