### ISSUE TITLE
import setuptools to create package that plays nice with pip

### ISSUE THREAD

**Issue by davidovitch** [jameskermode/f90wrap#34]
Currently, ```setup.py``` uses ```setup``` from ```numpy.distutils```:
```python
from numpy.distutils.core import setup, Extension
from numpy.distutils.system_info import get_info
```
However, you can still rely on ```setuptools``` in combination with ```numpy.distutils``` (which is required for the compiled extensions). This happens when ```setuptools``` is imported before ```numpy.distutils```:
```python
import setuptools
from numpy.distutils.core import setup, Extension
from numpy.distutils.system_info import get_info
```

I am not aware of the details, but I found in an old mailing list entry [1] that ```numpy.distutils``` figures out ```import setuptools``` happened before its own import and therefore magic happens... The result is still the same, but now the packaging is just slightly cleaner and you can actually properly uninstall f90wrap with pip from a virtual environment. I think the latter is real bonus.

[1] http://comments.gmane.org/gmane.comp.python.f2py.user/707

**Comment by jameskermode** [comment]
Happy to change this, but I guess it creates a new dependancy on setuptools. How widely installed is this, do you think? Maybe

```python
try:
    import setuptools
except ImportError:
    pass
from numpy.distutils.core import setup, Extension
from numpy.distutils.system_info import get_info
```

would be OK?

**Comment by davidovitch** [comment]
I don't know exactly how hard a dependency that is. Since it is optional, your solution seems to be perfectly harmless.

**Comment by jameskermode** [comment]
Done, let me know of any problems!
