### ISSUE TITLE
Array of derived_type makes function skipped, without any warning

### ISSUE THREAD

**Issue by MrYann** [jameskermode/f90wrap#42]
If a function uses an array of some derived type, the function is simply skipped by f90wrap, and no warning is issued.
Minimal example : 

module module_calcul
type type_ptmes
	integer :: y
end type type_ptmes
contains
subroutine recup_point(x)
type(type_ptmes) :: x(2)
return
end subroutine recup_point
end module module_calcul

**Comment by jameskermode** [comment]
A warning is printed if you run in verbose mode (``f90wrap -v``). 

The mechanism used to pass opaque references to derived types between Fortran and Python does not support arrays of derived types. As a workaround, one-dimensional arrays of derived types are supported within other derived types, e.g.:

```fortran
module module_calcul
type type_ptmes
integer :: y
end type type_ptmes
type array_type
type(type_ptmes) :: x(2)
end type array_type
contains
subroutine recup_point(x)
type(array_type) :: x
return
end subroutine recup_point
end module module_calcul
```

**Comment by MrYann** [comment]
Again, I thank you for your work and your support !

I tried this, and it seems to work. Note that calls to x inside the subroutine also have to be modified : 
x(1)%y has to be replaced by x%x(1)%y.

Could this be automated in the f90wrap_module.f90 file ? 
- replace all "type(type_name) :: x" arguments by "type_array :: x" arguments
- replace all x(some_index) by x%array(some_index) in the call to the function of the original module
- define the "type_name_array" type by "
        type type_name_array 
             type(type_name) :: array(n) 
        end type type_name_array
- infer the "n" for the type_name_array size from the allocation that has to be somewhere in the f90 files

**Comment by jameskermode** [comment]
This is an interesting idea, but I don't know how intuitive it would be users. I guess it's no worse than what we already do to pass around opaque types as integer array references. I won't have time to implement this anytime soon unfortunately, but as always I'm happy to look at a pull request.

**Comment by MrYann** [comment]
Fixed for 1-D fixed-lengh arrays. Maybe we close ?

**Comment by jameskermode** [comment]
Yup, closing for now. If someone needs this for 2D arrays please open a new issue.
