### ISSUE TITLE
implicit arguments are skipped, resulting in compilation error

### ISSUE THREAD

**Issue by MrYann** [jameskermode/f90wrap#44]
Hi James. As it is, I am still struggling to use some fortran code in Python ...

It seems that implicit arguments are skipped in the f90wrap files, instead of following the fortran implicit declaration rules (which f2py seems to know). Is there something I am missing, or do I have to explicitly declare all subroutine arguments ?

**Comment by jameskermode** [comment]
There's currently no support for implicit arguments in f90wrap, as I never came across a Fortran code which used these, but as usual I'm open to issues/pull requests :-)

**Comment by MrYann** [comment]
Your code is huge, so it is hard to tell but I guess that 2 small modifications might do it : 
1 - in file "f90wrapgen.py", function "visit_Procedure", line 332 : comment "self.write("implicit none")"
2 - in file "parse.py", function "check_subt", probably in the block starting at line 726, after the comment "Select only first declaration that matches entries in argument list" : find a way to keep the undeclared arguments.
3 - Repeat 2 for the function "check_funct"
Optional : give the type "implicit" to undeclared arguments for the doc_string.

It is of course the step 2 that is the most involved and I have not enough understanding of your code today to propose an precise way to do this.

**Comment by MrYann** [comment]
Hi James :)
I have tinkered a bit with your code to add basic inference of implicit types for arguments and function returns. Would you like me to provide the modified code, in the event of a future integration ? (I also "upgraded" some "removing this or that" lines from logging to warning, as I feel that missing functionalities should really be noted)

**Comment by jameskermode** [comment]
Please do, that would be great! If you create a pull request here on GitHub I will review your changes and incorporate as soon as possible.

**Comment by MrYann** [comment]
Ok, I tried, but must have done something wrong : it says +2487 -0 lines, and I have only added < 20 lines.
____
Yann

**Comment by MrYann** [comment]
Got it … uploaded in wring folder. Sorry for the inconvenience. 
____
Yann
