### ISSUE TITLE
--only and --skip switches bug

### ISSUE THREAD

**Issue by MrYann** [jameskermode/f90wrap#51]
Hi James : )
The --only and --skip are buggy: 
The "kept_modules" variable is defined in the file "f90wrap.py" as a set, to ensure a non-redundant list along the various appends.
But sets only work for hashable object. So the "Module" class needs a "__hash()__" function for your code to work as intended. All seems to work by adding the following function to the "Module" class, in the "fortran.py" file:

    # Required for the Module object to be hashable so one can create sets of Modules
    # So this function should return a unique imprint of the object.
    # I guess the filename + the module name should be unique enough ?
    # Also, hash requires an integer, so we convert the characters to integers with the
    # same number of digits to ensure one-to-one conversion.
    # This is maybe unnecessarily long ?
    def __hash__(self):
        return int(''.join(str(ord(x)).zfill(3) for x in self.filename + self.name))

I felt the is not worth a complete pull request, especially since I am tinkering with other files to handle arrays of derived types.

**Comment by jameskermode** [comment]
Closing issue as this is included in pull request #52
