### ISSUE TITLE
Support for non-default argument follows default argument

### ISSUE THREAD

**Issue by nelsyeung** [jameskermode/f90wrap#53]
Currently Fortran supports optional arguments before default arguments, see program below:

```fortran
program test
  call wrap(def = 2)

  contains

  subroutine wrap(opt, def)
    implicit none

    integer :: def
    integer, optional :: opt

    print *, 'present(opt) = ', present(opt)
    print *, 'def = ', def

    if (present(opt)) print *, 'opt = ', opt

  end subroutine
end program test
```

This compiles and runs fine.
f90wrap also runs fine:
```sh
f90wrap -m test main.F90
```

But if I import the program:
```sh
$ python

>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/theory/phukgm/Documents/test/test.py", line 5
    def wrap(opt=None, def_):
            ^
SyntaxError: non-default argument follows default argument
>>>
```

Is it possible to add optional before default arguments support to this module?

**Comment by jameskermode** [comment]
Thanks for reporting, I'm sure we can come up with a fix. As you can see, Python does not allow optional arguments to come before non-optional ones. One possible solution would be to re-order the arguments, so the Python interface to the function above would become ``wrap(def_, opt=None)``. Would that be an acceptable solution?

(By the way, as a quick work around, if you don't need access to the routines that are causing this problem, you could omit them from the wrapper generation with the ``--skip`` argument to f90wrap.)

**Comment by nelsyeung** [comment]
Thank you very much for your reply.

> One possible solution would be to re-order the arguments, so the Python interface to the function above would become wrap(def_, opt=None). Would that be an acceptable solution?

That was exactly the solution I was thinking so it's definitely an acceptable solution.

> (By the way, as a quick work around, if you don't need access to the routines that are causing this problem, you could omit them from the wrapper generation with the --skip argument to f90wrap.)

Unfortunately, it's in some pretty big part of the program so we can't just skip them.

**Comment by nelsyeung** [comment]
@jameskermode Just wondering whether you have any update on this? I'm thinking of writing a script which would reorder the variables during build time myself, if you are currently working on this and are making progress then I guess I'd wait.

**Comment by jameskermode** [comment]
Hi Nelson, sorry, I didn't manage to work on this yet. I'd hope to be able to do it in the next week or so. 

Rather than writing a script to modify your Fortran, if I point you to the relevant part of the `f90wrap` code would you be willing to try to add this feature directly? You would need to add a new subclass of `FortranVisitor` to `transform.py` and call this from `transform_to_py_wrapper`. The new class should be similar to `RenameArgumentsPython` but should instead re-order the arguments so any optionals come at the end.

**Comment by jameskermode** [comment]
Should now be fixed - as is often the case, it was not much work when I got round to it! 

I added a version of your test case as a `examples/optional_args_issue53`, and this is now working correctly. (Note that I had to change from a program to a standalone subroutine to get it to link correctly but this is unrelated to the wrapping issue).

I will leave this issue open for the moment,so you can let me know of any further problems, but if all is well we can close it soon.

**Comment by nelsyeung** [comment]
Sorry for the late reply. I can't actually get f90wrap working again. Following my details in this issue, I will get the error:
```
ImportError: /home/theory/phukgm/Documents/test/_test.so: undefined symbol: wrap_
```

For ONETEP, I'm getting the error
```
ImportError: dynamic module does not define init function (PyInit__onetep)
```

I feel like this is simply a setup issue with my system, but I can't quite figure out what.

**Comment by jameskermode** [comment]
I think the first error may be due to how you set up the Fortran code to be wrapped. Can you try to build the example in `f90wrap/examples/optional_args_issue53` by running `make` from that directory?

**Comment by nelsyeung** [comment]
I get `ImportError: dynamic module does not define init function (PyInit_sizeof_fortran_t)` during the make process.

**Comment by jameskermode** [comment]
Fixed (in person rather than on Github!). Problem as a mixture of Python 2 and 3, and of intel and GNU compilers.
