### ISSUE TITLE
"different_types" mismatch in test_set_derived_type(__main__.LibTests)

### ISSUE THREAD

**Issue by adcroft** [jameskermode/f90wrap#63]
In test_set_derived_type(self) in derivedtypes/tests.py, the line
```python
self.assert_(isinstance(dt, self.lib.datatypes.different_types))
```
passes for LibTestsPkg (for which `lib = ExampleDerivedTypes_pkg`) but FAILS for LibTests (for which `lib = ExampleDerivedTypes`).

`type(dt)` gives
> <class 'ExampleDerivedTypes_pkg.datatypes.different_types'>

for both LibTests and LibTestsPkg but `self.lib.datatypes.different_types` can be either
> <class 'ExampleDerivedTypes.Datatypes.different_types'>
> <class 'ExampleDerivedTypes_pkg.datatypes.different_types'>

for LibTests and LibTestsPkg respectively, and which are not the same. Hence `isinstance(dt, ...)` is False for LibTests and the assertion fails.

This is one of four failures running `make test`, and seen in Travis build [169.5](https://travis-ci.org/jameskermode/f90wrap/jobs/214660032), with commit 04d81b52f72.

**Comment by jameskermode** [comment]
Now fixed - sorry for the delay. Problem was that the package and module ways of building the wrapper lead to different FortranDerivedType subclasses with the same name. I now raise an exception if this occurs, and have changed the tests so that the module and package modes are tested sequentially.
