### ISSUE TITLE
Wrong wrapping subroutine with  the `BIND(C)` attribute

### ISSUE THREAD

**Issue by yagweb** [jameskermode/f90wrap#65]
When wrapping a procedure which has a `BIND(C, NAME='XXX')` attribute,  the "bind, c, name and XXX" are put in the arguments list of the generated procedure.

**Comment by jameskermode** [comment]
Thanks for reporting - iso_c_binding is not yet fully supported. Patches/pull requests welcome!

**Comment by yagweb** [comment]
Thank you for your prompt response. I will give a try to fix this.

**Comment by jameskermode** [comment]
Thanks for the PR!
