### ISSUE TITLE
where is the executable f90wrap.exe file on windows10

### ISSUE THREAD

**Issue by ChaoyiZhu93** [jameskermode/f90wrap#88]
I have installed f90wrap by cloning the repository from GitHub and running the setup.py script in anaconda prompt. The f90wrap can already be imported in python as module however the f90wrap can not be found if I call it directly in the anaconda prompt (or terminal). error message below:
'f90wrap' is not recognized as an internal or external command, operable program or batch file.
can not find the usable f90wrap.exe file to be added as environment variable

**Comment by jameskermode** [comment]
You might need to add whichever directory the script had been copied to to your PATH. For example, if you installed with `python setup.py install —user` this would be `~/.local/bin`

**Comment by ChaoyiZhu93** [comment]
I just installed it on my mac using the same method and there is no problem running f90wrap. the f90wrap executable in mac is in the /anaconda/bin.

On my windows laptop, the f90wrap is in the /anaconda/script along with the f2py. I can run f2py on the terminal but not the f90wrap.

**Comment by jameskermode** [comment]
Sorry, I’ve not used anaconda on Windows and no nothing about how paths are specified there. Must be a general issue though, not specific to f90wrap. It sounds like you need to add /anaconda/scripts to the console search path, but I don’t know how to do this in Windows.

**Comment by ChaoyiZhu93** [comment]
Thanks for the prompt reply. This tool will be very helpful for my work to wrap around a huge fortran90 repository. If it temporarily doesn't work out on the windows, I will just stick with my mac.

In fact, I already added the directory /anaconda/scripts to my PATH otherwise the f2py wouldn't be able to run. However, the f2py is in the format of an executable file .exe whereas the f90wrap does not have a file extension ..

**Comment by pakachiku** [comment]
I would also like a solution to this problem. There is not executable generated in this path, I find only the these files under the Scripts folder: f90wrap, f90doc, f2py-script.py and f2py-f90wrap. Is there any way to compile them into an executable?

**Comment by jameskermode** [comment]
As above, I’ve not used Python in general of f90wrap in particular on Windows so am unable to help. If anyone else can make a suggestion that would be great. It should not be necessary to build an executable, since these are standard Python scripts, and if necessary could be invoked as `python f90wrap` etc, but I’m sure there’s a better solution than that.

**Comment by bilderbuchi** [comment]
In principle conda packages should just pick up the `scripts` entry from setup.py (that was broken some time around 2016, see https://github.com/conda/conda-build/pull/1471), so that should work. However, the f90wrap recipe is not built on Windows, sadly.
