### ISSUE TITLE
AttributeError("'Prototype' object has no attribute 'mod_name'",)

### ISSUE THREAD

**Issue by ashleyzcy** [jameskermode/f90wrap#89]
File "/Users/chaoyizhu/anaconda/lib/python3.6/site-packages/f90wrap/pywrapgen.py", line 456, in visit_Interface
    proc_name += proc.mod_name.title() + '.'
AttributeError: 'Prototype' object has no attribute 'mod_name'
f90wrap: AttributeError("'Prototype' object has no attribute 'mod_name'",)

I am using f90wrap for a library of fortran source code. I got the above error message. what are the things to check in order to fix this error?

**Comment by jameskermode** [comment]
Thanks for reporting. If you provide a minimal example which demonstrates this problem I'll take a look.

**Comment by jameskermode** [comment]
Does anything need to be fixed in f90wrap?

If not, please close this issue.

**Comment by jameskermode** [comment]
Closing, please reopen if there’s something to fix.
