### ISSUE TITLE
f2py-f90wrap: undefined reference to `__intrinsic_setjmpex' when linking to build the module

### ISSUE THREAD

**Issue by jmp75** [jameskermode/f90wrap#96]
This happened whether I was using `gcc` or the MS visual studio cpp compiler `cl` for the makefile `CC` variable; when building the module linking fails.

```bat
C:\MinGW\mingw64\bin\gfortran.exe -Wall -g -Wall -g -shared .\Release\.\src.win-amd64-3.7\_waafmodule.o .\Release\.\src.win-amd64-3.7\.\src.win-amd64-3.7\fortranobject.o .\Release\cback.o .\Release\f90wrap_cback.o [...] .\Release\src.win-amd64-3.7\_WAAF-f2pywrappers2.o [...] -L. -LC:\MinGW\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0 [...] -lpython37 -lgfortran -o .\_WAAF.cp37-win_amd64.pyd
```

That is happening after already fixing an error with unknown SINGINT ( see #73 ) by including a `signal.h` header file

```c++
#include <signal.h>
```

On a hunch I replaced  `#include <setjmp.h>` with `#include <setjmpex.h>` and the module then compiled and loaded in Python.

I'll adjust `f2py-f90wrap` and submit a pull request.

**Comment by jameskermode** [comment]
Please close if this has been fully addressed by #97

**Comment by nenanth** [comment]
I think there is something here that breaks compilation for 32-bit python and toolchains (I just tested it). we may need setjmp.h for 32-bit and setjmpex.h for 64 bit

**Comment by nenanth** [comment]
Also relevant are the instructions to build a new python3*.dll in case the one provided by (e.g.) Anaconda has some import errors for Python objects
https://stackoverflow.com/questions/33069783/f2py-with-windows-7-64-bit
