### ISSUE TITLE
AttributeError: 'Prototype' object has no attribute 'mod_name'  on visit_Interface

### ISSUE THREAD

**Issue by jmp75** [jameskermode/f90wrap#98]
I am applying f90wrap on a new codebase and came across that error. This seems to have been reported in #89 and closed (no repro info). the `visit_interface` function seems to expect this attribute on the object so likely a design flaw. I will see if I can diagnose further.

**Comment by jmp75** [comment]
This seems caused by declarations as below. Forgot how interfaces work on Fortran so not yet in a position to reduce to a minimal example. I have to work around it for now and progress work but will see if I can repro later on.

```fortran
module BlahModule
!     lintrpl:   real function linear Interpolation and extrapolation
      implicit none

      public

      interface lintrpl
        module procedure lintrpl_real
        module procedure lintrpl_dble
      end interface

      contains
```

**Comment by jameskermode** [comment]
Thanks for reporting and for the workaround. Would you be willing to adapt this into to a pull request?
